language: php
sudo: false
php:
  - 8.0
  - 8.1
before_script:
  - composer install -n
script:
  - export XDEBUG_MODE=coverage
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_script:
  - if [ $TRAVIS_PHP_VERSION = '8.1' ]; then php vendor/bin/php-coveralls; fi
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/test-reporter